//
//  TransitionView.swift
//  
//
//  Created by Deka Primatio on 17/08/22.
//

import UIKit

class TransitionView: UIView {
    
    // Images View Properties
    private lazy var imageView: UIImageView = {
        let view = UIImageView()
        view.contentMode = .scaleAspectFill
        view.clipsToBounds = true
        view.backgroundColor = .yellow
        return view
    }()
    
    // Array for Bar Animations Depends on How Many Images Added inside the Assets
    private lazy var barViews: [AnimatedBarView] = {
        var views: [AnimatedBarView] = []
        slides.forEach { _ in
            views.append(AnimatedBarView())
        }
        return views
    }()
    
    /**
     * Instance for Encapsulation Stacks barView Images from Client
     * Whatever the Client passes via this light object we are going to generate
     * Number of barViews as needed for the screen it self, then distribute the bar size equally
     */
    private lazy var barStackView: UIStackView = {
        let stackView = UIStackView()
        barViews.forEach { barView in
            stackView.addArrangedSubview(barView)
        }
        stackView.axis = .horizontal
        stackView.spacing = 8
        stackView.distribution = .fillEqually
        return stackView
    }()
    
    // Title View Properties
    private lazy var titleView: TitleView = {
        let view = TitleView()
        return view
    }()
    
    // Instance for Encapsulation Stacks imageView & titleView above
    private lazy var stackView: UIStackView = {
        let stackView = UIStackView(arrangedSubviews: [imageView, titleView])
        stackView.distribution = .fill
        stackView.axis = .vertical
        return stackView
    }()
    
    // To Connect with Slide & viewTintColor Depedencies in Controller
    private let slides: [Slide]
    private let viewTintColor: UIColor
    
    // Internal Init for TransitionView
    init(slides: [Slide], tintColor: UIColor) {
        self.slides = slides
        self.viewTintColor = tintColor
        super.init(frame: .zero)
        transitionLayout()
    }
    
    // Default Required Init Generated by Xcode
    required init?(coder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }
    
    // Callback Function for TransitionView with Auto Layout
    private func transitionLayout() {
        addSubview(stackView)
        addSubview(barStackView)
        
        stackView.snp.makeConstraints { make in
            make.edges.equalTo(self)
        }
        
        // Making barStackView below the Groove Front Camera & Inside the ImageView
        barStackView.snp.makeConstraints { make in
            make.leading.equalTo(snp.leading).offset(24)
            make.trailing.equalTo(snp.trailing).offset(-24)
            make.top.equalTo(snp.topMargin)
            make.height.equalTo(4)
        }
        
        // Making ImageView Taking 80% of the Entire Height
        imageView.snp.makeConstraints { make in
            make.height.equalTo(stackView.snp.height).multipliedBy(0.8)
        }
    }
}
